by_load: 
  0HP: 
    - "97DE"

    - "105DE"
    - "169DE"
    - "209DE"

    - "130DE"
    - "234DE"
    - "144DE"  
    - "156DE"  
    - "246DE"  
    - "258DE"
  1HP:
    - "98DE"

    - "106DE"
    - "170DE"
    - "210DE"

    - "131DE"
    - "235DE"
    - "145DE"
    - "158DE"
    - "247DE"
    - "259DE"
  2HP:
    - "99DE"

    - "107DE"
    - "171DE"
    - "211DE"

    - "132DE"
    - "236DE"
    - "146DE"
    - "159DE"
    - "248DE"
    - "260DE"
  3HP:
    - "100DE"

    - "108DE"
    - "172DE"
    - "212DE"

    - "133DE"
    - "237DE"
    - "147DE"
    - "160DE"
    - "249DE"
    - "261DE"

by_load_balanced:
  0HP: 
    - "97DE"

    - "105DE"
    - "169DE"
    - "209DE"

    - "130DE"
    - "234DE"
    - "144DE"  
    
  1HP:
    - "98DE"

    - "106DE"
    - "170DE"
    - "210DE"

    - "131DE"
    - "235DE"
    - "145DE"

  2HP:
    - "99DE"

    - "107DE"
    - "171DE"
    - "211DE"

    - "132DE"
    - "236DE"
    - "146DE"

  3HP:
    - "100DE"

    - "108DE"
    - "172DE"
    - "212DE"

    - "133DE"
    - "237DE"
    - "147DE"

by_bearing: 
  S007: 
    - "105DE"
    - "106DE"
    - "107DE"
    - "108DE"

    - "144DE"
    - "145DE"
    - "146DE"
    - "147DE"

    - "130DE"
    - "131DE"
    - "132DE"
    - "133DE"

    - "156DE"
    - "158DE"
    - "159DE"
    - "160DE"
  S014:
    - "169DE"
    - "170DE"
    - "171DE"
    - "171DE"
  S021:
    - "209DE"
    - "210DE"
    - "211DE"
    - "212DE"

    - "246DE"
    - "247DE"
    - "248DE"
    - "249DE"

    - "234DE"
    - "235DE"
    - "236DE"
    - "237DE"

    - "258DE"
    - "259DE"
    - "260DE"
    - "261DE"

  Normal: 
    - "97DE"
    - "98DE"
    - "99DE"
    - "100DE"

